## 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

In [10]:
import os
import numpy as np
import pandas as pd

np.set_printoptions(threshold=np.inf)
# pd.set_option('display.height', 1000)
# pd.set_option('display.max_rows', 500)
# pd.set_option('display.max_columns', 500)
# pd.set_option('display.width', 1000)

In [2]:
# 設定 data_path
dir_data = r'C:\Users\user\Desktop\Kaggle\Credit'

In [3]:
f_app = os.path.join(dir_data, 'application_train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: C:\Users\user\Desktop\Kaggle\Credit\application_train.csv

### 如果沒有想法，可以先嘗試找出剛剛例子中提到的問題的答案
#### 資料的 row 數以及 column 數

In [4]:
app_train.shape

(307511, 122)

#### 列出所有欄位

In [15]:
np.asarray(app_train.columns)

array(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN',
       'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE',
       'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE',
       'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE',
       'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED',
       'DAYS_REGISTRATION', 'DAYS_ID_PUBLISH', 'OWN_CAR_AGE',
       'FLAG_MOBIL', 'FLAG_EMP_PHONE', 'FLAG_WORK_PHONE',
       'FLAG_CONT_MOBILE', 'FLAG_PHONE', 'FLAG_EMAIL', 'OCCUPATION_TYPE',
       'CNT_FAM_MEMBERS', 'REGION_RATING_CLIENT',
       'REGION_RATING_CLIENT_W_CITY', 'WEEKDAY_APPR_PROCESS_START',
       'HOUR_APPR_PROCESS_START', 'REG_REGION_NOT_LIVE_REGION',
       'REG_REGION_NOT_WORK_REGION', 'LIVE_REGION_NOT_WORK_REGION',
       'REG_CITY_NOT_LIVE_CITY', 'REG_CITY_NOT_WORK_CITY',
       'LIVE_CITY_NOT_WORK_CITY', 'ORGANIZATION_TYPE', 'EXT_SOURCE_1',
       'EXT_SOURCE_2', 'EXT_SOURCE_3', 'APARTMENTS_AVG',
       'BASEMENTAREA_AVG', 'YEARS_BEGINEXPLUATATION_AVG',
       'YEARS_BUILD_AVG', 'COMMONAREA_AVG', 'ELEVATORS_AVG',
       'ENTRANCES_AVG', 'FLOORSMAX_AVG', 'FLOORSMIN_AVG', 'LANDAREA_AVG',
       'LIVINGAPARTMENTS_AVG', 'LIVINGAREA_AVG',
       'NONLIVINGAPARTMENTS_AVG', 'NONLIVINGAREA_AVG', 'APARTMENTS_MODE',
       'BASEMENTAREA_MODE', 'YEARS_BEGINEXPLUATATION_MODE',
       'YEARS_BUILD_MODE', 'COMMONAREA_MODE', 'ELEVATORS_MODE',
       'ENTRANCES_MODE', 'FLOORSMAX_MODE', 'FLOORSMIN_MODE',
       'LANDAREA_MODE', 'LIVINGAPARTMENTS_MODE', 'LIVINGAREA_MODE',
       'NONLIVINGAPARTMENTS_MODE', 'NONLIVINGAREA_MODE',
       'APARTMENTS_MEDI', 'BASEMENTAREA_MEDI',
       'YEARS_BEGINEXPLUATATION_MEDI', 'YEARS_BUILD_MEDI',
       'COMMONAREA_MEDI', 'ELEVATORS_MEDI', 'ENTRANCES_MEDI',
       'FLOORSMAX_MEDI', 'FLOORSMIN_MEDI', 'LANDAREA_MEDI',
       'LIVINGAPARTMENTS_MEDI', 'LIVINGAREA_MEDI',
       'NONLIVINGAPARTMENTS_MEDI', 'NONLIVINGAREA_MEDI',
       'FONDKAPREMONT_MODE', 'HOUSETYPE_MODE', 'TOTALAREA_MODE',
       'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE',
       'OBS_30_CNT_SOCIAL_CIRCLE', 'DEF_30_CNT_SOCIAL_CIRCLE',
       'OBS_60_CNT_SOCIAL_CIRCLE', 'DEF_60_CNT_SOCIAL_CIRCLE',
       'DAYS_LAST_PHONE_CHANGE', 'FLAG_DOCUMENT_2', 'FLAG_DOCUMENT_3',
       'FLAG_DOCUMENT_4', 'FLAG_DOCUMENT_5', 'FLAG_DOCUMENT_6',
       'FLAG_DOCUMENT_7', 'FLAG_DOCUMENT_8', 'FLAG_DOCUMENT_9',
       'FLAG_DOCUMENT_10', 'FLAG_DOCUMENT_11', 'FLAG_DOCUMENT_12',
       'FLAG_DOCUMENT_13', 'FLAG_DOCUMENT_14', 'FLAG_DOCUMENT_15',
       'FLAG_DOCUMENT_16', 'FLAG_DOCUMENT_17', 'FLAG_DOCUMENT_18',
       'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20', 'FLAG_DOCUMENT_21',
       'AMT_REQ_CREDIT_BUREAU_HOUR', 'AMT_REQ_CREDIT_BUREAU_DAY',
       'AMT_REQ_CREDIT_BUREAU_WEEK', 'AMT_REQ_CREDIT_BUREAU_MON',
       'AMT_REQ_CREDIT_BUREAU_QRT', 'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype=object)

#### 截取部分資料

In [16]:
app_train[app_train['NAME_INCOME_TYPE'] == 'Working']

        SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  AMT_GOODS_PRICE  NAME_TYPE_SUITE NAME_INCOME_TYPE            NAME_EDUCATION_TYPE    NAME_FAMILY_STATUS    NAME_HOUSING_TYPE  REGION_POPULATION_RELATIVE  DAYS_BIRTH  DAYS_EMPLOYED  DAYS_REGISTRATION  DAYS_ID_PUBLISH  OWN_CAR_AGE  FLAG_MOBIL  FLAG_EMP_PHONE  FLAG_WORK_PHONE  FLAG_CONT_MOBILE  FLAG_PHONE  FLAG_EMAIL        OCCUPATION_TYPE  CNT_FAM_MEMBERS  REGION_RATING_CLIENT  REGION_RATING_CLIENT_W_CITY WEEKDAY_APPR_PROCESS_START  HOUR_APPR_PROCESS_START  REG_REGION_NOT_LIVE_REGION  REG_REGION_NOT_WORK_REGION  LIVE_REGION_NOT_WORK_REGION  REG_CITY_NOT_LIVE_CITY  REG_CITY_NOT_WORK_CITY  LIVE_CITY_NOT_WORK_CITY       ORGANIZATION_TYPE  EXT_SOURCE_1  EXT_SOURCE_2  EXT_SOURCE_3  APARTMENTS_AVG  BASEMENTAREA_AVG  YEARS_BEGINEXPLUATATION_AVG  YEARS_BUILD_AVG  COMMONAREA_AVG  ELEVATORS_AVG  ENTRANCES_AVG  FLOORSMAX_AVG  FLOORSMIN_AVG  LANDAREA_AVG  \
0           100002       1         Cash loans           M            N               Y             0          202500.0    406597.5      24700.5         351000.0    Unaccompanied          Working  Secondary / secondary special  Single / not married    House / apartment                    0.018801       -9461           -637            -3648.0            -2120          NaN           1               1                0                 1           1           0               Laborers              1.0                     2                            2                  WEDNESDAY                       10                           0                           0                            0                       0                       0                        0  Business Entity Type 3      0.083037      0.262949      0.139376          0.0247            0.0369                       0.9722           0.6192          0.0143         0.0000         0.0690         0.0833         0.1250        0.0369
2           100004       0    Revolving loans           M            Y               Y             0           67500.0    135000.0       6750.0         135000.0    Unaccompanied          Working  Secondary / secondary special  Single / not married    House / apartment                    0.010032      -19046           -225            -4260.0            -2531         26.0           1               1                1                 1           1           0               Laborers              1.0                     2                            2                     MONDAY                        9                           0                           0                            0                       0                       0                        0              Government           NaN      0.555912      0.729567             NaN               NaN                          NaN              NaN             NaN            NaN            NaN            NaN            NaN           NaN
3           100006       0         Cash loans           F            N               Y             0          135000.0    312682.5      29686.5         297000.0    Unaccompanied          Working  Secondary / secondary special        Civil marriage    House / apartment                    0.008019      -19005          -3039            -9833.0            -2437          NaN           1               1                0                 1           0           0               Laborers              2.0                     2                            2                  WEDNESDAY                       17                           0                           0                            0                       0                       0                        0  Business Entity Type 3           NaN      0.650442           NaN             NaN               NaN                          NaN              NaN             NaN            NaN            NaN            NaN            NaN           NaN
4           100007       0         Cash loans           M            N               Y             0          121500.0    513000.0      21865.5         513000.0    Unaccompanied          Working  Secondary / secondary special  Single / not married    House / apartment                    0.028663      -19932          -3038            -4311.0            -3458          NaN           1               1                0                 1           0           0             Core staff              1.0                     2                            2                   THURSDAY                       11                           0                           0                            0                       0                       1                        1                Religion           NaN      0.322738           NaN             NaN               NaN                          NaN              NaN             NaN            NaN            NaN            NaN            NaN           NaN
9           100012       0    Revolving loans           M            N               Y             0          135000.0    405000.0      20250.0         405000.0    Unaccompanied          Working  Secondary / secondary special  Single / not married    House / apartment                    0.019689      -14469          -2019           -14437.0            -3992          NaN           1               1                0                 1           0           0               Laborers              1.0                     2                            2                   THURSDAY                        8                           0                           0                            0                       0                       0                        0             Electricity           NaN      0.746644           NaN             NaN               NaN                          NaN              NaN             NaN            NaN            NaN            NaN            NaN           NaN
10          100014       0         Cash loans           F            N               Y             1          112500.0    652500.0      21177.0         652500.0    Unaccompanied          Working               Higher education               Married    House / apartment                    0.022800      -10197           -679            -4427.0             -738          NaN           1               1                0                 1           0           0             Core staff              3.0                     2                            2                   SATURDAY                       15                           0                           0                            0                       0                       0                        0                Medicine      0.319760      0.651862      0.363945             NaN               NaN                          NaN              NaN             NaN            NaN            NaN            NaN            NaN           NaN
12          100016       0         Cash loans           F            N               Y             0           67500.0     80865.0       5881.5          67500.0    Unaccompanied          Working  Secondary / secondary special               Married    House / apartment                    0.031329      -13439          -2717             -311.0            -3227          NaN           1               1                1                 1           1           0               Laborers              2.0                     2                            2                     FRIDAY                       10                           0                           0                            0                       0                       0                        0  Business Entity Type 2      0.464831      0.715042      0.176653          0.0825               NaN                       0.9811              NaN             NaN         0.0000         0.2069         0.1667            NaN        0.0135
13          100017       0         Cash loans           M            Y               N             1          225000.0    918468.0      28966.5         697500.0    Unaccompanied          Working  Secondary / secondary special               Married    House / apartment                    0.016612      -14086          -3028             -643.0            -4911         23.0           1               1                0                 1           0           0                Drivers              3.0                     2                            2                   THURSDAY                       13                           0                           0                            0                       0                       0                        0           Self-employed           NaN      0.566907      0.770087          0.1474            0.0973                       0.9806           0.7348          0.0582         0.1600         0.1379         0.3333         0.3750        0.0931
14          100018       0         Cash loans           F            N               Y             0          189000.0    773680.5      32778.0         679500.0    Unaccompanied          Working  Secondary / secondary special               Married    House / apartment                    0.010006      -14583           -203             -615.0            -2056          NaN           1               1                0                 1           0           0               Laborers              2.0                     2                            1                     MONDAY                        9                           0                           0                            0                       0                       0                        0       Transport: type 2      0.721940      0.642656           NaN          0.3495            0.1335                       0.9985           0.9796          0.1143         0.4000         0.1724         0.6667         0.7083        0.1758
15          100019       0         Cash loans           M            Y               Y             0          157500.0    299772.0      20160.0         247500.0           Family          Working  Secondary / secondary special  Single / not married     Rented apartment                    0.020713       -8728          -1157            -3494.0            -1368         17.0           1               1                0                 1           0           0               Laborers              1.0                     3                            3                   SATURDAY                        6                           0                           0                            0                       1                       1                        0  Business Entity Type 2      0.115634      0.346634      0.678568             NaN               NaN                          NaN              NaN             NaN            NaN            NaN            NaN            NaN           NaN
16          100020       0         Cash loans           M            N               N             0          108000.0    509602.5      26149.5         387000.0    Unaccompanied          Working  Secondary / secondary special               Married    House / apartment                    0.018634      -12931          -1317            -6392.0            -3866          NaN           1               1                0                 1           0           0                Drivers              2.0                     2                            2                   THURSDAY                       12                           0                           0                            0                       1                       1                        0              Government           NaN      0.236378      0.062103             NaN               NaN                          NaN              NaN             NaN            NaN            NaN            NaN            NaN           NaN
17          100021       0    Revolving loans           F            N               Y             1           81000.0    270000.0      13500.0         270000.0    Unaccompanied          Working  Secondary / secondary special               Married    House / apartment                    0.010966       -9776           -191            -4143.0            -2427          NaN           1               1                0                 1           0           0               Laborers              3.0                     2                            2                     MONDAY                       10                           0                           0                            0                       1                       1                        0            Construction           NaN      0.683513           NaN             NaN               NaN                          NaN              NaN             NaN            NaN            NaN            NaN            NaN           NaN
18          100022       0    Revolving loans           F            N               Y             0          112500.0    157500.0       7875.0         157500.0          Other_A          Working  Secondary / secondary special                 Widow    House / apartment                    0.046220      -17718          -7804            -8751.0            -1259          NaN           1               1                0                 1           1           0               Laborers              1.0                     1                            1                     FRIDAY                       13                           0                           0                            0                       0                       0                        0                 Housing           NaN      0.706428      0.556727          0.0278            0.0617                       0.9881           0.8368          0.0018         0.0000         0.1034         0.0833         0.1250        0.0279
20          100024       0    Revolving loans           M            Y               Y             0          135000.0    427500.0      21375.0         427500.0    Unaccompanied          Working  Secondary / secondary special               Married    House / apartment                    0.015221      -18252          -4286             -298.0            -1800          7.0           1               1                0                 1           0           0               Laborers              2.0                     2                            2                     FRIDAY                       13                           0                           0                            0                       0                       0                        0           Self-employed      0.565655      0.113375           NaN          0.0722            0.0801                       0.9781           0.7008             NaN         0.0000         0.1379         0.1667         0.0417        0.0534
22          100026       0         Cash loans           F            N               N             1          450000.0    497520.0      32521.5         450000.0    Unaccompanied          Working  Secondary / secondary special               Married     Rented apartment                    0.020713      -11146          -4306             -114.0            -2518          NaN           1               1                0                 1           0           0            Sales staff              3.0                     3                            2                   THURSDAY                        6                           0                           0                            0                       0                       0                        0           Self-employed           NaN      0.457143      0.358951          0.0907            0.0795                       0.9786           0.7076          0.0120         0.0000         0.2069         0.1667         0.2083        0.0898
24          100029       0         Cash loans           M            Y               N             2          135000.0    247500.0      12703.5         247500.0    Unaccompanied          Working  Secondary / secondary special               Married    House / apartment                    0.026392      -11286           -746             -108.0            -3729          7.0           1               1                0                 1           0           0                Drivers              4.0                     2                            2                   THURSDAY                       14                           0                           0                            0                       0                       1                        1  Business Entity Type 3           NaN      0.786179      0.565608          0.1433            0.1455                       0.9861           0.8096          0.0212         0.0000         0.3103         0.1667         0.2083        0.0861
25          100030       0         Cash loans           F            N               Y             0           90000.0    225000.0      11074.5         225000.0    Unaccompanied          Working  Secondary / secondary special               Married    House / apartment                    0.028663      -19334          -3494            -2419.0            -2893          NaN           1               1                0                 1           1           0         Cleaning staff              2.0                     2                            2                   SATURDAY                        8                           0                           0                            0                       0                       0                        0  Business Entity Type 3      0.561948      0.651406      0.461482          0.0722            0.0147                       0.9781           0.7008          0.0010         0.0000         0.1379         0.1667         0.0417        0.0498
26          100031       1         Cash loans           F            N               Y             0          112500.0    979992.0      27076.5         702000.0    Unaccompanied          Working  Secondary / secondary special                 Widow    House / apartment                    0.018029      -18724          -2628            -6573.0            -1827          NaN           1               1                0                 1           0           0          Cooking staff              1.0                     3                            2                     MONDAY                        9                           0                           0                            0                       0                       0                        0  Business Entity Type 3           NaN      0.548477      0.190706          0.0165            0.0089                       0.9732              NaN             NaN         0.0000         0.0690         0.0417            NaN        0.0265
27          100032       0         Cash loans           M            N               Y             1          112500.0    327024.0      23827.5         270000.0           Family          Working  Secondary / secondary special               Married    House / apartment                    0.019101      -15948          -1234            -5782.0            -3153          NaN           1               1                0                 1           0           0               Laborers              3.0                     2                            2                   SATURDAY                       10                           0                           0                            0                       0                       1                        1       Industry: type 11           NaN      0.541124      0.659406             NaN               NaN                          NaN              NaN             NaN            NaN            NaN            NaN            NaN           NaN

#### 還有各種數之不盡的資料操作，重點還是取決於實務中遇到的狀況和你想問的問題，在馬拉松中我們也會陸續提到更多例子